version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9567632a
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  admin-backend:
    build:
      context: ./admin-console
    container_name: admin-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  admin-frontend:
    build:
      context: ./admin-console/frontend
      dockerfile: Dockerfile
    container_name: admin-frontend
    ports:
      - "3000:80"
    depends_on:
      - admin-backend
    networks:
      - backend

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
